### PR TITLE
Fix specialized classes conflict resolver

### LINKED ISSUE #78: TypeLoader#load_project failing when a T::Struct has a nested class
**Describe the bug**
`Parlour::TypeLoader.load_project` fails when a T::Struct has a nested class defined outside of the original class body.

**To Reproduce**
```ruby
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A < T::Struct; end
  class A::B; end
RUBY

# Called within `load_project`
Parlour::ConflictResolver.new.resolve_conflicts(namespace) do |n, o|
  raise "conflict of #{o.length} objects: #{n}"
end
```

**Expected behavior**
No conflict

**Actual behavior**
Conflict

**Additional information**
I think what's happening is that when the loader encounters `A::B` it creates a top-level `A` child but without a subclass so the conflict resolution thinks they're different. This doesn't happen when the original `A` is a subclass of some other class which makes me think this is specific to T::Struct. Some other things I tried:

Using the "expanded" nesting still doesn't work.
```ruby
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A < T::Struct; end

  class A
    class B; end
  end
RUBY
```

Explicitly subclass from T::Struct again works
```ruby
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A < T::Struct; end

  class A < T::Struct
    class B; end
  end
RUBY
```

Non-T::Struct works:
```ruby
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A < Foo; end
  class A::B; end
RUBY
```

### PR DESCRIPTION
**Pull request by jeffcarbs**
Fixes #78 

~Want to confirm this works on my codebase with no regressions.~ Confirmed 🙂 

Fixing conflict resolution in specialized namespaces (i.e. Enum and Struct). Some notable changes:
- Handle merging a plain `ClassNamespace` with one of the specialized ones
- Handle merging multiple of the same specialized namespaces if they have the either the same enums/props (or some are empty).
- When merging multiple specialized namespaces choose the non-empty enums/props.
- Fix issue where load order of plain `ClassNamespace` vs the specialized ones would affect mergeability (i.e. say things were mergeable when they shouldn't be).

Wanted to call out the last commit which specifically orders the namespaces when using the `differing_namespaces` strategy. I found cases where a module namespace was getting dropped when generating RBI and realized it was due to a `Namespace` occurring  before a `ModuleNamespace` with the same name. I fixed and added a test that exercised the bug.

### CODE REVIEW

File: lib/parlour/type_parser.rb [hunk 1]
```diff
@@ -234,7 +234,7 @@ def parse_path_to_object(path, is_within_eigenclass: false)
         elsif ['T::Enum', '::T::Enum'].include?(node_to_s(superclass))
           # Look for (block (send nil :enums) ...) structure
           enums_node = body.nil? ? nil :
-            body.to_a.find { |x| x.type == :block && x.to_a[0].type == :send && x.to_a[0].to_a[1] == :enums }
+            (body.type == :begin ? body.to_a : [body]).find { |x| x.type == :block && x.to_a[0].type == :send && x.to_a[0].to_a[1] == :enums }
```
Comment (jeffcarbs) [inline lib/parlour/type_parser.rb:237]: Fixed a bug when `enums` was an empty block, e.g.
```
class X < T::Enum
  enum do
  end
end
```

**Comment by AaronC81** [comment]
Looks good! Thank you very much for looking into implementing this - I'm glad it's finally resolved :smiley:
